services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - .:/app
      - ./logs:/app/src/logs
    depends_on:
      - db_zeppelin
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    command: supervisord -c /etc/supervisord.conf

  db_zeppelin:
    image: postgres:15
    container_name: db_zeppelin
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:7
    container_name: redis_zeppelin
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
